"""
Markdown Report - clean pentest-ready export
"""

from datetime import datetime


CATEGORY_TITLES = {
    "attack_surface": "Attack Surface",
    "exposed_assets": "Exposed Assets",
    "tech_stack": "Technology Stack",
    "internal_tools": "Internal Tools",
    "employee_intel": "Employee Intelligence",
    "security_posture": "Security Posture",
    "temporal_insights": "Temporal Insights",
}

CONF_EMOJI = {"HIGH": "🔴", "MEDIUM": "🟡", "LOW": "🔵"}


def _finding_md(f, index: int) -> str:
    lines = []
    conf_icon = CONF_EMOJI.get(f.confidence, "⚪")
    risk = getattr(f, "risk_score", 0.0)
    lines.append(f"### {index}. {f.title}")
    lines.append(f"**Confidence:** {conf_icon} {f.confidence} &nbsp; **Risk Score:** `{risk}/10`")
    lines.append("")
    lines.append(f.description)
    if f.inference_chain:
        lines.append("")
        lines.append(f"> **Inference:** {f.inference_chain}")
    if f.attack_relevance:
        lines.append("")
        lines.append(f"**Attack Relevance:** {f.attack_relevance}")
    if f.cves_or_techniques:
        lines.append("")
        descs = getattr(f, "cve_descriptions", {})
        cve_items = []
        for c in f.cves_or_techniques:
            desc = descs.get(c, "")
            if desc:
                cve_items.append(f"- `{c}` — {desc}")
            else:
                cve_items.append(f"- `{c}`")
        lines.append("**CVEs / Techniques:**")
        lines.extend(cve_items)
    if f.evidence_sources:
        lines.append("")
        lines.append(f"*Sources: {', '.join(f.evidence_sources)}*")
    lines.append("")
    lines.append("---")
    return "\n".join(lines)


def _section_md(category: str, findings: list) -> str:
    if not findings:
        return ""
    title = CATEGORY_TITLES.get(category, category.replace("_", " ").title())
    lines = [f"## {title}", ""]
    for i, f in enumerate(findings, 1):
        lines.append(_finding_md(f, i))
    return "\n".join(lines) + "\n"


def generate_markdown_report(report) -> str:
    all_findings = (
        report.tech_stack + report.internal_tools + report.employee_intel +
        report.security_posture + report.attack_surface +
        report.exposed_assets + report.temporal_insights
    )
    total = len(all_findings)
    high = sum(1 for f in all_findings if f.confidence == "HIGH")
    medium = sum(1 for f in all_findings if f.confidence == "MEDIUM")
    low = sum(1 for f in all_findings if f.confidence == "LOW")
    cve_count = sum(1 for f in all_findings for c in f.cves_or_techniques if c.upper().startswith("CVE-"))
    score = report.security_maturity_score

    lines = []
    lines.append(f"# Semantic Recon Report — {report.target} ({report.domain})")
    lines.append(f"*Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')} | For authorized use only*")
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("## Executive Summary")
    lines.append("")
    lines.append(report.summary or "No summary available.")
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("## Statistics")
    lines.append("")
    lines.append(f"| Metric | Value |")
    lines.append(f"|--------|-------|")
    lines.append(f"| Total Findings | {total} |")
    lines.append(f"| High Confidence | 🔴 {high} |")
    lines.append(f"| Medium Confidence | 🟡 {medium} |")
    lines.append(f"| Low Confidence | 🔵 {low} |")
    lines.append(f"| CVEs Found | {cve_count} |")
    lines.append(f"| Security Maturity Score | {score}/10 |")
    lines.append("")
    lines.append("---")
    lines.append("")

    for category, findings in [
        ("attack_surface", report.attack_surface),
        ("exposed_assets", report.exposed_assets),
        ("tech_stack", report.tech_stack),
        ("internal_tools", report.internal_tools),
        ("employee_intel", report.employee_intel),
        ("security_posture", report.security_posture),
        ("temporal_insights", report.temporal_insights),
    ]:
        section = _section_md(category, findings)
        if section:
            lines.append(section)

    lines.append("---")
    lines.append("*Generated by Semantic Recon Engine*")
    return "\n".join(lines)


def save_markdown_report(report, filepath: str):
    md = generate_markdown_report(report)
    with open(filepath, "w", encoding="utf-8") as f:
        f.write(md)
